[package]
name = "agorapp-solana"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
lto = true
debug = false
strip = true
panic = "abort"
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[dependencies]
axum = { version = "0.7.4", features = ["tokio", "json", "http1"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.0", features = ["macros", "sync", "net", "io-util", "rt-multi-thread", "process"], default-features = false}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
http = "1.0.0"
lazy_static = "1.4.0"
anyhow = "1.0.80"
dirs = "5.0.1"
regex = "1.10.3"
fs_extra = "1.3.0"
