[package]
name = "solana-lesson-introduction"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18.6"
spl-token = { version = "4.0", features = [ "no-entrypoint" ] }
signature = "1.6.4"

[dev-dependencies]
solana-program-test = "1.18.6"
solana-sdk = "1.18.6"

[lib]
crate-type = ["cdylib", "lib"]
